config:
  prequel:githubToken:
    secure: AAABAFY7xLaEZTaGRE97Ogjy1w1VIoLZi1cg1LV5rsXB8k8F7R0nSReLeVPWY4vADeVIAZm1LyxitvBp2IT2nsbAovoMw8RnLlTsAFvPqh0mOKuDxBKoMcruhHADqnX0MW8fr8BGSzQuhA6jojB60OMD2r/x5dXpd/0s4LV+ug==
  prequel:githubWebhookSecret:
    secure: AAABALWwG4o4l1oF0JiKtXgLyi+9bFHZrSOXdPuBk/DmjYpovSSuAjhppqXwBHBbz3/FU56hom0amfN+nKso0Ptspo5x5huN
  prequel:slackWebhookUrl:
    secure: AAABAH4O1usMe7Z/MnUhtociIH3N/UYxi3Z5k4yOJsnJckCEZnD89rHaDZzZaeeUBagUYCYZCpEwt3rX/O4M0umeJrqSFHBMesLHlXOTy7E3VUDNnh6A9SBUzGSof5vrxZCi9AxH90Ll73DA1TwNS4E=
  prequel:vmAdminUsername: vmadmin
  prequel:vmAdminPassword:
    secure: AAABAE1J1t3feswpgfOJgcn80oC1syYn7LLcQa+v1Whj0wuZ+oZHBwbIPjaoB8gSWpvBRmFtH8k=
  prequel:sqlAdminUsername: prequel_admin
  prequel:sqlAdminPassword:
    secure: AAABAAFyU6rcwFSC1t9oK42Fe1ZzjcXCKkkA6elPzeoWEw5bX/XJTjTh7gXAQtbrFUxT9JS7CrM=
  prequel:location: Central India
  prequel:organizationName: Shetchuko
  azure-native:clientId: ""
  azure-native:clientSecret:
    secure: AAABAH6JNP0h/MC2G446D2oMpl6FuExDPmGImWw7ejw=
  azure-native:tenantId: ""
  azure-native:subscriptionId: ""
