config:
  prequel:githubToken:
    secure: AAABAHhi9lf6CONX4Vm8zZA8tRh38o/MwiTMGYTTwl7+Ub/1wUceuGgGjjX1FJ+xL3007KUzYHamk2a1sjmvbBuhjXgrnE7Y01NSXbpGwRwBvXXgCkj6oRwfJN+eNBp+alTQboOy850SSs+Agnr5f22MPeNukImzoDyPQC8=
  prequel:githubWebhookSecret:
    secure: AAABAMB757+VO/9uTKz6A3TqgNb2drnRInu9x+dJViIDrROOFO5AZGl1sb3KBdvp9GlZiai4fjDdCVNqdFMxwcVVASJFjnwh
  prequel:slackWebhookUrl:
    secure: AAABAAMM5SprgHNjhxjrdUagKNPhnkP3O/lZCRxSz5zDhjdtPifOj0+Uh4TN+xV4u7B9QJxmOAcz71htLrz3aqgt9K7FW8Vlk9tXdZgW0X07CFZbKyXNJlxSeGcEHSQDgUm2I8Ch2nQV5ndzdm17Lis=
  prequel:vmAdminUsername: vmadmin
  prequel:vmAdminPassword:
    secure: AAABAIGr/OtYFkiHBQkw0ZVk2+/PBXhPyIrAET+32owDvPKHXDFWjbOpKWh8z5Y8gyHh+/4X3VM=
  prequel:sqlAdminUsername: prequel_admin
  prequel:sqlAdminPassword:
    secure: AAABAMVe86+LMr18OzC8p5DQKoIZPw3qLuwE61yDSPeFBJoBdT08HMjKklNUmka3mTi148MGxhU=
  prequel:location: Central India
  prequel:organizationName: Shetchuko
